# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/steven/projects/tmp/h5cpp-cmake;/home/steven/projects/tmp/h5cpp-cmake")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.15)")
set(CPACK_DEBIAN_PACKAGE_ENHANCES "libhdf5-dev,libhdf5-serial-dev")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://h5cpp.org")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_SUGGESTS "libhdf5-dev,libhdf5-serial-dev")
set(CPACK_GENERATOR "DEB")
set(CPACK_INSTALLED_DIRECTORIES "/home/steven/projects/tmp/h5cpp-cmake/build;usr")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/steven/projects/tmp/h5cpp-cmake;h5cpp-dev;ALL;/")
set(CPACK_INSTALL_COMMANDS "env PREFIX=build make install")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/steven/projects/tmp/h5cpp-cmake/cmake/;/home/steven/projects/tmp/h5cpp-cmake/cmake/eigen3;/home/steven/projects/tmp/h5cpp-cmake/cmake/dlib")
set(CPACK_NSIS_DISPLAY_NAME "h5cpp-dev 1.10.4.1")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "h5cpp-dev 1.10.4.1")
set(CPACK_OUTPUT_CONFIG_FILE "/home/steven/projects/tmp/h5cpp-cmake/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Steven Varga <steven@vargaconsulting.ca>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "H5CPP header only component to provide high performance HDF5 serialisation/persistance for modern C++ ")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "HDF5 persistence for modern C++")
set(CPACK_PACKAGE_FILE_NAME "-1.10.4.1-")
set(CPACK_PACKAGE_HOMEPAGE_URL "http://h5cpp.org")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "h5cpp-dev 1.10.4.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "h5cpp-dev 1.10.4.1")
set(CPACK_PACKAGE_NAME "h5cpp-dev")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "vargaconsulting.ca")
set(CPACK_PACKAGE_VERSION "1.10.4.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "10")
set(CPACK_PACKAGE_VERSION_PATCH "4")
set(CPACK_PACKAGE_VERSION_TWEAK "1")
set(CPACK_PROPERTIES_FILE "/home/steven/projects/tmp/h5cpp-cmake/CPackProperties.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/local/share/cmake-3.13/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "DEB")
set(CPACK_SOURCE_IGNORE_FILES "./build/;./.bzr/;")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/steven/projects/tmp/h5cpp-cmake/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "h5cpp-dev-1.10.4.1")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "1")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/steven/projects/tmp/h5cpp-cmake/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
