.TH H5CPP 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
h5cpp \- compiles HDF5 compound datatype descriptors from C++ AST
.SH SYNOPSIS
.B h5cpp translation_unit.cpp --$(CXXFLAGS) -Doutput.h

.SH "DESCRIPTION"
LLVM based compiler builds AST from specified TU translation unit and compiles
HDF5 compound datatype descriptors for variables marked with 
h5::create | h5::read | h5::write | h5::append or
h5::acreate | h5::aread | h5::awrite operators


.SH OPTIONS
.TP
.B -D
output filename to be generated
.TP
.B -v
verbose invocation of the underlying clang tooling framework to aid you with 
identifying search paths, etc...
.TP
.B -e
error messages are suppressed by default, since the TU translation unit is incomplete. This flag 
will re-enable clang error reports

.SH EXAMPLES
.TP
.B h5cpp translation_unit.cpp -- $(CXXFLAGS)  -Dgenerated.h

will build AST from translation_unit.cpp and create HDF5 compound descriptors in generated.h

.SH CAVEATS
h5cpp compiler doesn't report error but silently fails if the input is incorrect generating an empty file.
The rationale behind this behaviour that the input is incomplete because of the missing compound datatype descriptors
and trips clang internal error reporting even with the correct input.


.SH AUTHOR
steven varga <steven@vargaconsulting.ca>

