var searchData=
[
  ['h5_0',['h5',['../namespaceh5.html',1,'']]],
  ['h5_3a_3a_20attribute_20vocabulary_20hdf5_20backend_1',['h5:: Attribute Vocabulary (HDF5 Backend)',['../reports_compiler_h5_attribute_taxonomy.html',1,'reports_index']]],
  ['h5_3a_3acreate_2',['h5::create',['../curated_io_api_file_create.html',1,'curated_io_api_file']]],
  ['h5_3a_3aopen_3',['h5::open',['../curated_io_api_file_open.html',1,'curated_io_api_file']]],
  ['h5cpp_20—_20modern_20c_20for_20hdf5_4',['H5CPP — Modern C++ for HDF5',['../index.html',1,'']]],
  ['h5cpp_20compiler_20multi_20backend_20architecture_5',['h5cpp-compiler Multi-Backend Architecture',['../reports_compiler_multi_backend_architecture.html',1,'reports_index']]],
  ['h5cpp_20compiler_20prior_20art_20survey_6',['h5cpp-compiler Prior Art Survey',['../reports_compiler_prior_art_survey.html',1,'reports_index']]],
  ['h5cpp_20filter_20inventory_20use_20guide_7',['H5CPP Filter Inventory &amp; Use Guide',['../reports_filters_inventory.html',1,'reports_index']]],
  ['h5cpp_20handle_20inventory_20pretty_20print_20status_8',['H5CPP Handle Inventory &amp; Pretty-Print Status',['../reports_handle_inventory.html',1,'reports_index']]],
  ['h5cpp_20multithreaded_20filter_20pipeline_20—_20current_20state_20v1_2012_207_9',['h5cpp Multithreaded Filter Pipeline — Current State (v1.12.7)',['../reports_multithreading_pipeline_state.html',1,'reports_index']]],
  ['h5cpp_20operations_10',['Basic H5CPP Operations',['../example_guide_basics.html',1,'examples_guides_index']]],
  ['h5cpp_20stl_20pretty_20print_20guide_11',['H5CPP STL Pretty-Print Guide',['../reports_stl_pretty_print_guide.html',1,'reports_index']]],
  ['h5cpp_20type_20system_20map_20—_20today_20s_20reality_12',['h5cpp Type-System Map — Today&apos;s Reality',['../reports_type_system_map.html',1,'reports_index']]],
  ['h5cpp_20usability_20evaluation_13',['h5cpp Usability Evaluation',['../reports_usability_evaluation.html',1,'reports_index']]],
  ['half_20float_20support_14',['half float support',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2christian-rau_2README.html',1,'half float support'],['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2open-exr_2README.html',1,'Industrial Light and Magick - OpenEXR half float support']]],
  ['half_20precision_20floats_20—_20third_20party_20variants_15',['Half-Precision Floats — Third-Party Variants',['../example_guide_half_float.html',1,'examples_guides_index']]],
  ['handle_20inventory_20pretty_20print_20status_16',['H5CPP Handle Inventory &amp; Pretty-Print Status',['../reports_handle_inventory.html',1,'reports_index']]],
  ['handles_17',['handles',['../link_handle_reference.html#handle_ref_async',1,'Async-mode handles'],['../example_guide_cout.html',1,'cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles'],['../link_handle_reference.html#handle_ref_objects',1,'Object handles'],['../group__io-wrap.html',1,'RAII handles'],['../link_raii_idiom.html',1,'RAII Handles'],['../link_handle_reference.html#handle_ref_references',1,'Reference handles'],['../link_base_template_types.html#types_references',1,'Reference handles']]],
  ['handles_20descriptors_20property_20lists_18',['Handles, Descriptors &amp; Property Lists',['../link_handle_reference.html',1,'']]],
  ['handles_20use_20which_20policy_19',['Which handles use which policy',['../link_conversion_policy.html#conversion_inventory',1,'']]],
  ['handling_20',['Error Handling',['../link_error_handler.html',1,'']]],
  ['hardware_5fconcurrency_21',['hardware_concurrency',['https://en.cppreference.com/cpp/thread/thread/hardware_concurrency',1,'std::thread']]],
  ['has_5ffacet_22',['has_facet',['https://en.cppreference.com/cpp/locale/has_facet',1,'std']]],
  ['has_5fvirtual_5fdestructor_23',['has_virtual_destructor',['https://en.cppreference.com/cpp/types/has_virtual_destructor',1,'std']]],
  ['hash_24',['hash',['https://en.cppreference.com/cpp/utility/hash',1,'std::hash'],['https://en.cppreference.com/cpp/locale/collate/hash',1,'std::collate_byname::hash()'],['https://en.cppreference.com/cpp/utility/hash/hash',1,'std::hash::hash()'],['https://en.cppreference.com/cpp/locale/collate/hash',1,'std::collate::hash()']]],
  ['hash_5fcode_25',['hash_code',['https://en.cppreference.com/cpp/types/type_index/hash_code',1,'std::type_index::hash_code()'],['https://en.cppreference.com/cpp/types/type_info/hash_code',1,'std::type_info::hash_code()']]],
  ['hash_5ffunction_26',['hash_function',['https://en.cppreference.com/cpp/container/unordered_map/hash_function',1,'std::unordered_map::hash_function()'],['https://en.cppreference.com/cpp/container/unordered_multimap/hash_function',1,'std::unordered_multimap::hash_function()'],['https://en.cppreference.com/cpp/container/unordered_multiset/hash_function',1,'std::unordered_multiset::hash_function()'],['https://en.cppreference.com/cpp/container/unordered_set/hash_function',1,'std::unordered_set::hash_function()']]],
  ['hdf5_27',['hdf5',['../example_guide_csv.html',1,'CSV to HDF5'],['../index.html',1,'H5CPP — Modern C++ for HDF5']]],
  ['hdf5_20attributes_28',['HDF5 attributes',['../group__attribute-io.html',1,'']]],
  ['hdf5_20backend_29',['h5:: Attribute Vocabulary (HDF5 Backend)',['../reports_compiler_h5_attribute_taxonomy.html',1,'reports_index']]],
  ['hdf5_20datasets_30',['HDF5 datasets',['../group__datasets.html',1,'']]],
  ['hdf5_20error_20stack_31',['Muting the native HDF5 error stack',['../link_error_handler.html#error_mute',1,'']]],
  ['hdf5_20files_32',['HDF5 files',['../group__file-io.html',1,'']]],
  ['hdf5_20property_20lists_20dataspaces_20hyperslab_20arguments_20and_20handles_33',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['hdf5_20related_20bugs_34',['Top 10 Most Frequent HDF5-Related Bugs',['../reports_study_hdf5_bugs_top10.html',1,'reports_index']]],
  ['hdf5_20serialisation_35',['Reflection — Compiler-Assisted HDF5 Serialisation',['../example_guide_reflection.html',1,'examples_guides_index']]],
  ['hecto_36',['hecto',['https://en.cppreference.com/cpp/numeric/ratio/ratio',1,'std']]],
  ['hex_37',['hex',['https://en.cppreference.com/cpp/io/manip/hex',1,'std']]],
  ['hexfloat_38',['hexfloat',['https://en.cppreference.com/cpp/io/manip/fixed',1,'std']]],
  ['hierarchy_39',['hierarchy',['../link_error_handler.html#error_hierarchy',1,'Exception hierarchy'],['../link_error_handler.html#error_rollback',1,'The rollback hierarchy']]],
  ['high_5fresolution_5fclock_40',['high_resolution_clock',['https://en.cppreference.com/cpp/chrono/high_resolution_clock',1,'std::chrono']]],
  ['hours_41',['hours',['https://en.cppreference.com/cpp/chrono/duration/duration',1,'std::chrono::hours::hours()'],['https://en.cppreference.com/cpp/chrono/duration',1,'std::chrono::hours']]],
  ['how_20dispatch_20works_42',['how dispatch works',['../link_linalg_template_types.html#linalg_dispatch',1,'How dispatch works'],['../link_base_template_types.html#types_dispatch',1,'How dispatch works']]],
  ['hpp_20attribute_20vocabulary_43',['pb.hpp Attribute Vocabulary',['../reports_compiler_pb_attribute_taxonomy.html',1,'reports_index']]],
  ['hyperslab_20arguments_20and_20handles_44',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['hypot_45',['hypot',['https://en.cppreference.com/cpp/numeric/math/hypot',1,'std']]]
];
