var searchData=
[
  ['v1_2012_207_0',['h5cpp Multithreaded Filter Pipeline — Current State (v1.12.7)',['../reports_multithreading_pipeline_state.html',1,'reports_index']]],
  ['va_5flist_1',['va_list',['https://en.cppreference.com/cpp/utility/variadic/va_list',1,'']]],
  ['valarray_2',['valarray',['https://en.cppreference.com/cpp/numeric/valarray',1,'std']]],
  ['valid_3',['valid',['https://en.cppreference.com/cpp/thread/shared_future/valid',1,'std::shared_future::valid()'],['https://en.cppreference.com/cpp/thread/future/valid',1,'std::future::valid()'],['https://en.cppreference.com/cpp/thread/packaged_task/valid',1,'std::packaged_task::valid()']]],
  ['value_4',['value',['https://en.cppreference.com/cpp/error/error_code/value',1,'std::error_code::value()'],['https://en.cppreference.com/cpp/regex/regex_traits/value',1,'std::regex_traits::value()'],['https://en.cppreference.com/cpp/error/error_condition/value',1,'std::error_condition::value()'],['https://en.cppreference.com/cpp/experimental/optional/value',1,'std::experimental::optional::value()']]],
  ['value_5fcomp_5',['value_comp',['https://en.cppreference.com/cpp/container/multiset/value_comp',1,'std::multiset::value_comp()'],['https://en.cppreference.com/cpp/container/set/value_comp',1,'std::set::value_comp()'],['https://en.cppreference.com/cpp/container/map/value_comp',1,'std::map::value_comp()'],['https://en.cppreference.com/cpp/container/multimap/value_comp',1,'std::multimap::value_comp(T... args)']]],
  ['value_5fcompare_6',['value_compare',['https://en.cppreference.com/cpp/container/multimap/value_compare',1,'std::multimap::value_compare'],['https://en.cppreference.com/cpp/container/map/value_compare',1,'std::map::value_compare']]],
  ['value_5for_7',['value_or',['https://en.cppreference.com/cpp/experimental/optional/value_or',1,'std::experimental::optional']]],
  ['variable_20length_20and_20ragged_20shapes_8',['Variable-length and ragged shapes',['../link_base_template_types.html#types_ragged',1,'']]],
  ['variants_9',['Half-Precision Floats — Third-Party Variants',['../example_guide_half_float.html',1,'examples_guides_index']]],
  ['vector_10',['vector',['https://en.cppreference.com/cpp/container/vector',1,'std::vector'],['https://en.cppreference.com/cpp/container/vector/vector',1,'std::vector::vector()']]],
  ['vectors_20—_20csc_20round_20trip_11',['Sparse Matrices &amp; Vectors — CSC Round-Trip',['../example_guide_sparse.html',1,'examples_guides_index']]],
  ['vfd_20ros3_12',['S3 example — Read-Only S3 VFD (ROS3)',['../example_guide_s3.html',1,'examples_guides_index']]],
  ['vfprintf_13',['vfprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vfscanf_14',['vfscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vfwprintf_15',['vfwprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vfwscanf_16',['vfwscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]],
  ['views_20c_2023_20p0009_20round_20trip_17',['mdspan — Non-Owning N-D Views, C++23 P0009 Round-Trip',['../example_guide_mdspan.html',1,'examples_guides_index']]],
  ['vlen_20round_20trip_20across_20datasets_20and_20attributes_18',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['vocabulary_19',['vocabulary',['../aliases_reference.html',1,'Doxygen alias vocabulary'],['../reports_compiler_pb_attribute_taxonomy.html',1,'pb.hpp Attribute Vocabulary']]],
  ['vocabulary_20avro_20backend_20',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20bson_20backend_21',['bson:: Attribute Vocabulary (BSON Backend)',['../reports_compiler_bson_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20cbor_20backend_22',['cbor:: Attribute Vocabulary (CBOR Backend)',['../reports_compiler_cbor_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20hdf5_20backend_23',['h5:: Attribute Vocabulary (HDF5 Backend)',['../reports_compiler_h5_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20json_20schema_20backend_24',['json:: Attribute Vocabulary (JSON Schema Backend)',['../reports_compiler_json_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20messagepack_20backend_25',['msgpack:: Attribute Vocabulary (MessagePack Backend)',['../reports_compiler_msgpack_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20rlp_20backend_26',['rlp:: Attribute Vocabulary (RLP Backend)',['../reports_compiler_rlp_attribute_taxonomy.html',1,'reports_index']]],
  ['vocabulary_20sql_20backend_27',['sql:: Attribute Vocabulary (SQL Backend)',['../reports_compiler_sql_attribute_taxonomy.html',1,'reports_index']]],
  ['vprintf_28',['vprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vscanf_29',['vscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vsnprintf_30',['vsnprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vsprintf_31',['vsprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vsscanf_32',['vsscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vswprintf_33',['vswprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vswscanf_34',['vswscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]],
  ['vwprintf_35',['vwprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vwscanf_36',['vwscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]]
];
