var searchData=
[
  ['a_0',['a',['https://en.cppreference.com/cpp/numeric/random/cauchy_distribution/params',1,'std::cauchy_distribution::a()'],['https://en.cppreference.com/cpp/numeric/random/uniform_int_distribution/params',1,'std::uniform_int_distribution::a()'],['https://en.cppreference.com/cpp/numeric/random/weibull_distribution/params',1,'std::weibull_distribution::a()'],['https://en.cppreference.com/cpp/numeric/random/uniform_real_distribution/params',1,'std::uniform_real_distribution::a()'],['https://en.cppreference.com/cpp/numeric/random/extreme_value_distribution/params',1,'std::extreme_value_distribution::a()']]],
  ['a_20glance_1',['Overview — supported libraries at a glance',['../link_linalg_template_types.html#linalg_quick_summary',1,'']]],
  ['abort_2',['abort',['https://en.cppreference.com/cpp/utility/program/abort',1,'std']]],
  ['abs_28float_29_3',['abs(float)',['https://en.cppreference.com/cpp/numeric/math/fabs',1,'std']]],
  ['abs_28int_29_4',['abs(int)',['https://en.cppreference.com/cpp/numeric/math/abs',1,'std']]],
  ['accumulate_5',['accumulate',['https://en.cppreference.com/cpp/algorithm/accumulate',1,'std']]],
  ['acos_6',['acos',['https://en.cppreference.com/cpp/numeric/math/acos',1,'std']]],
  ['acosh_7',['acosh',['https://en.cppreference.com/cpp/numeric/math/acosh',1,'std']]],
  ['across_20datasets_8',['References — Region &amp; Object Pointers Across Datasets',['../example_guide_reference.html',1,'examples_guides_index']]],
  ['across_20datasets_20and_20attributes_9',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['add_5fconst_10',['add_const',['https://en.cppreference.com/cpp/types/add_cv',1,'std']]],
  ['add_5fcv_11',['add_cv',['https://en.cppreference.com/cpp/types/add_cv',1,'std']]],
  ['add_5flvalue_5freference_12',['add_lvalue_reference',['https://en.cppreference.com/cpp/types/add_reference',1,'std']]],
  ['add_5fpointer_13',['add_pointer',['https://en.cppreference.com/cpp/types/add_pointer',1,'std']]],
  ['add_5frvalue_5freference_14',['add_rvalue_reference',['https://en.cppreference.com/cpp/types/add_reference',1,'std']]],
  ['add_5fvolatile_15',['add_volatile',['https://en.cppreference.com/cpp/types/add_cv',1,'std']]],
  ['address_16',['address',['https://en.cppreference.com/cpp/memory/allocator/address',1,'std::allocator']]],
  ['addressof_17',['addressof',['https://en.cppreference.com/cpp/memory/addressof',1,'std']]],
  ['adelete_18',['adelete',['../group__attribute-io.html#ga58a9ef1cfdd613c391057331373d74ee',1,'h5']]],
  ['adjacent_5fdifference_19',['adjacent_difference',['https://en.cppreference.com/cpp/algorithm/adjacent_difference',1,'std']]],
  ['adjacent_5ffind_20',['adjacent_find',['https://en.cppreference.com/cpp/algorithm/adjacent_find',1,'std']]],
  ['adopt_5flock_5ft_21',['adopt_lock_t',['https://en.cppreference.com/cpp/thread/lock_tag_t',1,'std']]],
  ['advance_22',['advance',['https://en.cppreference.com/cpp/iterator/advance',1,'std']]],
  ['algebra_23',['algebra',['../curated_topics_linalg.html',1,'LINEAR ALGEBRA'],['../link_base_template_types.html#types_linalg_sparse',1,'Sparse linear algebra']]],
  ['algebra_20containers_24',['Linear-Algebra Containers',['../example_guide_linalg.html',1,'examples_guides_index']]],
  ['algebra_20dense_20containers_25',['Linear-algebra dense containers',['../link_base_template_types.html#types_linalg_dense',1,'']]],
  ['algebra_20types_26',['Supported Linear Algebra Types',['../link_linalg_template_types.html',1,'']]],
  ['alias_20vocabulary_27',['Doxygen alias vocabulary',['../aliases_reference.html',1,'']]],
  ['align_28',['align',['https://en.cppreference.com/cpp/memory/align',1,'std']]],
  ['aligned_5fstorage_29',['aligned_storage',['https://en.cppreference.com/cpp/types/aligned_storage',1,'std']]],
  ['aligned_5funion_30',['aligned_union',['https://en.cppreference.com/cpp/types/aligned_union',1,'std']]],
  ['alignment_5fof_31',['alignment_of',['https://en.cppreference.com/cpp/types/alignment_of',1,'std']]],
  ['all_32',['all',['https://en.cppreference.com/cpp/utility/bitset/all_any_none',1,'std::bitset']]],
  ['all_20exception_20types_33',['All exception types',['../link_error_handler.html#error_types',1,'']]],
  ['all_5fof_34',['all_of',['https://en.cppreference.com/cpp/algorithm/all_any_none_of',1,'std']]],
  ['allocate_35',['allocate',['https://en.cppreference.com/cpp/memory/scoped_allocator_adaptor/allocate',1,'std::scoped_allocator_adaptor::allocate()'],['https://en.cppreference.com/cpp/memory/allocator_traits/allocate',1,'std::allocator_traits::allocate()'],['https://en.cppreference.com/cpp/memory/allocator/allocate',1,'std::allocator::allocate()']]],
  ['allocate_5fshared_36',['allocate_shared',['https://en.cppreference.com/cpp/memory/shared_ptr/allocate_shared',1,'std']]],
  ['allocator_37',['allocator',['https://en.cppreference.com/cpp/memory/allocator',1,'std::allocator'],['https://en.cppreference.com/cpp/memory/allocator/allocator',1,'std::allocator::allocator()']]],
  ['allocator_5farg_5ft_38',['allocator_arg_t',['https://en.cppreference.com/cpp/memory/allocator_arg_t',1,'std']]],
  ['allocator_5ftraits_39',['allocator_traits',['https://en.cppreference.com/cpp/memory/allocator_traits',1,'std']]],
  ['alpha_40',['alpha',['https://en.cppreference.com/cpp/numeric/random/gamma_distribution/params',1,'std::gamma_distribution']]],
  ['always_5fnoconv_41',['always_noconv',['https://en.cppreference.com/cpp/locale/codecvt/always_noconv',1,'std::codecvt_byname::always_noconv()'],['https://en.cppreference.com/cpp/locale/codecvt/always_noconv',1,'std::codecvt::always_noconv()'],['https://en.cppreference.com/cpp/locale/codecvt/always_noconv',1,'std::codecvt_utf8::always_noconv()'],['https://en.cppreference.com/cpp/locale/codecvt/always_noconv',1,'std::codecvt_utf8_utf16::always_noconv()'],['https://en.cppreference.com/cpp/locale/codecvt/always_noconv',1,'std::codecvt_utf16::always_noconv()']]],
  ['analysis_42',['#287 Multithreaded Pipeline — Profile &amp; Analysis',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2multithreaded-pipeline_2profile-report.html',1,'']]],
  ['and_20attributes_43',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['and_20datasets_44',['Attributes — Metadata on Groups and Datasets',['../example_guide_attributes.html',1,'examples_guides_index']]],
  ['and_20handles_45',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['and_20magick_20openexr_20half_20float_20support_46',['Industrial Light and Magick - OpenEXR half float support',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2open-exr_2README.html',1,'']]],
  ['and_20ragged_20shapes_47',['Variable-length and ragged shapes',['../link_base_template_types.html#types_ragged',1,'']]],
  ['and_20tt_20std_3a_3aarray_20tt_48',['C arrays and &lt;tt&gt;std::array&lt;/tt&gt;',['../link_base_template_types.html#types_arrays',1,'']]],
  ['and_20type_20conversion_20callbacks_49',['Transform — DXPL Expressions and Type-Conversion Callbacks',['../example_guide_transform.html',1,'examples_guides_index']]],
  ['any_50',['any',['https://en.cppreference.com/cpp/utility/bitset/all_any_none',1,'std::bitset']]],
  ['any_5fof_51',['any_of',['https://en.cppreference.com/cpp/algorithm/all_any_none_of',1,'std']]],
  ['api_52',['IO API',['../curated_io_api.html',1,'']]],
  ['append_53',['append',['https://en.cppreference.com/cpp/string/basic_string/append',1,'std::string::append()'],['https://en.cppreference.com/cpp/string/basic_string/append',1,'std::wstring::append()'],['https://en.cppreference.com/cpp/string/basic_string/append',1,'std::basic_string::append()'],['https://en.cppreference.com/cpp/string/basic_string/append',1,'std::u32string::append()'],['https://en.cppreference.com/cpp/string/basic_string/append',1,'std::u16string::append()'],['../example_guide_packet_table.html',1,'Packet Tables — Streaming Append']]],
  ['architecture_54',['architecture',['../curated_topics_architecture.html',1,'ARCHITECTURE'],['../reports_compiler_multi_backend_architecture.html',1,'h5cpp-compiler Multi-Backend Architecture']]],
  ['aread_55',['aread',['../group__attribute-io.html#ga7986986d558b0ae23902b6b917e5dce7',1,'h5']]],
  ['arguments_20and_20handles_56',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['armadillo_57',['Armadillo',['../link_linalg_template_types.html#linalg_arma',1,'']]],
  ['array_58',['array',['https://en.cppreference.com/cpp/container/array',1,'std']]],
  ['array_20t_20n_20tt_20of_20containers_59',['STL &lt;tt&gt;array&lt;T,N&gt;&lt;/tt&gt;-of containers',['../link_base_template_types.html#types_array_of',1,'']]],
  ['arrays_20and_20tt_20std_3a_3aarray_20tt_60',['C arrays and &lt;tt&gt;std::array&lt;/tt&gt;',['../link_base_template_types.html#types_arrays',1,'']]],
  ['art_20survey_61',['h5cpp-compiler Prior Art Survey',['../reports_compiler_prior_art_survey.html',1,'reports_index']]],
  ['asctime_62',['asctime',['https://en.cppreference.com/cpp/chrono/c/asctime',1,'std']]],
  ['asin_63',['asin',['https://en.cppreference.com/cpp/numeric/math/asin',1,'std']]],
  ['asinh_64',['asinh',['https://en.cppreference.com/cpp/numeric/math/asinh',1,'std']]],
  ['assign_65',['assign',['https://en.cppreference.com/cpp/utility/functional/function/assign',1,'std::function::assign()'],['https://en.cppreference.com/cpp/string/char_traits/assign',1,'std::char_traits::assign()'],['https://en.cppreference.com/cpp/string/basic_string/assign',1,'std::wstring::assign()'],['https://en.cppreference.com/cpp/error/error_condition/assign',1,'std::error_condition::assign()'],['https://en.cppreference.com/cpp/string/basic_string/assign',1,'std::u16string::assign()'],['https://en.cppreference.com/cpp/string/basic_string/assign',1,'std::u32string::assign()'],['https://en.cppreference.com/cpp/container/list/assign',1,'std::list::assign()'],['https://en.cppreference.com/cpp/string/basic_string/assign',1,'std::basic_string::assign()'],['https://en.cppreference.com/cpp/container/deque/assign',1,'std::deque::assign()'],['https://en.cppreference.com/cpp/error/error_code/assign',1,'std::error_code::assign()'],['https://en.cppreference.com/cpp/container/forward_list/assign',1,'std::forward_list::assign()'],['https://en.cppreference.com/cpp/regex/basic_regex/assign',1,'std::wregex::assign()'],['https://en.cppreference.com/cpp/regex/basic_regex/assign',1,'std::basic_regex::assign()'],['https://en.cppreference.com/cpp/container/vector/assign',1,'std::vector::assign()'],['https://en.cppreference.com/cpp/string/basic_string/assign',1,'std::string::assign()'],['https://en.cppreference.com/cpp/regex/basic_regex/assign',1,'std::regex::assign()']]],
  ['assisted_20hdf5_20serialisation_66',['Reflection — Compiler-Assisted HDF5 Serialisation',['../example_guide_reflection.html',1,'examples_guides_index']]],
  ['associative_20containers_67',['STL associative containers',['../link_base_template_types.html#types_stl_associative',1,'']]],
  ['async_68',['async',['https://en.cppreference.com/cpp/thread/async',1,'std']]],
  ['async_20mode_20—_20conversion_20deleted_20at_20the_20type_20level_69',['Async mode — conversion deleted at the type level',['../link_conversion_policy.html#conversion_async',1,'']]],
  ['async_20mode_20handles_70',['Async-mode handles',['../link_handle_reference.html#handle_ref_async',1,'']]],
  ['at_71',['at',['https://en.cppreference.com/cpp/container/array/at',1,'std::array::at()'],['https://en.cppreference.com/cpp/container/map/at',1,'std::map::at()'],['https://en.cppreference.com/cpp/string/basic_string/at',1,'std::u32string::at()'],['https://en.cppreference.com/cpp/string/basic_string/at',1,'std::u16string::at()'],['https://en.cppreference.com/cpp/string/basic_string/at',1,'std::wstring::at()'],['https://en.cppreference.com/cpp/string/basic_string/at',1,'std::basic_string::at()'],['https://en.cppreference.com/cpp/container/deque/at',1,'std::deque::at()'],['https://en.cppreference.com/cpp/container/unordered_map/at',1,'std::unordered_map::at()'],['https://en.cppreference.com/cpp/string/basic_string/at',1,'std::string::at()'],['https://en.cppreference.com/cpp/container/vector/at',1,'std::vector::at()'],['https://en.cppreference.com/cpp/container/dynarray/at',1,'std::dynarray::at()']]],
  ['at_20a_20glance_72',['Overview — supported libraries at a glance',['../link_linalg_template_types.html#linalg_quick_summary',1,'']]],
  ['at_20the_20type_20level_73',['Async mode — conversion deleted at the type level',['../link_conversion_policy.html#conversion_async',1,'']]],
  ['at_5fquick_5fexit_74',['at_quick_exit',['https://en.cppreference.com/cpp/utility/program/at_quick_exit',1,'std']]],
  ['atan_75',['atan',['https://en.cppreference.com/cpp/numeric/math/atan',1,'std']]],
  ['atan2_76',['atan2',['https://en.cppreference.com/cpp/numeric/math/atan2',1,'std']]],
  ['atanh_77',['atanh',['https://en.cppreference.com/cpp/numeric/math/atanh',1,'std']]],
  ['atexit_78',['atexit',['https://en.cppreference.com/cpp/utility/program/atexit',1,'std']]],
  ['atof_79',['atof',['https://en.cppreference.com/cpp/string/byte/atof',1,'std']]],
  ['atoi_80',['atoi',['https://en.cppreference.com/cpp/string/byte/atoi',1,'std']]],
  ['atol_81',['atol',['https://en.cppreference.com/cpp/string/byte/atoi',1,'std']]],
  ['atoll_82',['atoll',['https://en.cppreference.com/cpp/string/byte/atoi',1,'std']]],
  ['atomic_83',['atomic',['https://en.cppreference.com/cpp/atomic/atomic/atomic',1,'std::atomic::atomic()'],['https://en.cppreference.com/cpp/atomic/atomic',1,'std::atomic']]],
  ['atomic_5fcompare_5fexchange_5fstrong_84',['atomic_compare_exchange_strong',['https://en.cppreference.com/cpp/atomic/atomic_compare_exchange',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fstrong_5fexplicit_85',['atomic_compare_exchange_strong_explicit',['https://en.cppreference.com/cpp/atomic/atomic_compare_exchange',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_86',['atomic_compare_exchange_weak',['https://en.cppreference.com/cpp/atomic/atomic_compare_exchange',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_5fexplicit_87',['atomic_compare_exchange_weak_explicit',['https://en.cppreference.com/cpp/atomic/atomic_compare_exchange',1,'std']]],
  ['atomic_5fexchange_88',['atomic_exchange',['https://en.cppreference.com/cpp/atomic/atomic_exchange',1,'std']]],
  ['atomic_5fexchange_5fexplicit_89',['atomic_exchange_explicit',['https://en.cppreference.com/cpp/atomic/atomic_exchange',1,'std']]],
  ['atomic_5ffetch_5fadd_90',['atomic_fetch_add',['https://en.cppreference.com/cpp/atomic/atomic_fetch_add',1,'std']]],
  ['atomic_5ffetch_5fadd_5fexplicit_91',['atomic_fetch_add_explicit',['https://en.cppreference.com/cpp/atomic/atomic_fetch_add',1,'std']]],
  ['atomic_5ffetch_5fand_92',['atomic_fetch_and',['https://en.cppreference.com/cpp/atomic/atomic_fetch_sub',1,'std']]],
  ['atomic_5ffetch_5fand_5fexplicit_93',['atomic_fetch_and_explicit',['https://en.cppreference.com/cpp/atomic/atomic_fetch_sub',1,'std']]],
  ['atomic_5ffetch_5for_94',['atomic_fetch_or',['https://en.cppreference.com/cpp/atomic/atomic_fetch_or',1,'std']]],
  ['atomic_5ffetch_5for_5fexplicit_95',['atomic_fetch_or_explicit',['https://en.cppreference.com/cpp/atomic/atomic_fetch_or',1,'std']]],
  ['atomic_5ffetch_5fsub_96',['atomic_fetch_sub',['https://en.cppreference.com/cpp/atomic/atomic_fetch_sub',1,'std']]],
  ['atomic_5ffetch_5fsub_5fexplicit_97',['atomic_fetch_sub_explicit',['https://en.cppreference.com/cpp/atomic/atomic_fetch_sub',1,'std']]],
  ['atomic_5ffetch_5fxor_98',['atomic_fetch_xor',['https://en.cppreference.com/cpp/atomic/atomic_fetch_xor',1,'std']]],
  ['atomic_5ffetch_5fxor_5fexplicit_99',['atomic_fetch_xor_explicit',['https://en.cppreference.com/cpp/atomic/atomic_fetch_xor',1,'std']]],
  ['atomic_5fflag_100',['atomic_flag',['https://en.cppreference.com/cpp/atomic/atomic_flag',1,'std::atomic_flag'],['https://en.cppreference.com/cpp/atomic/atomic_flag/atomic_flag',1,'std::atomic_flag::atomic_flag()']]],
  ['atomic_5finit_101',['atomic_init',['https://en.cppreference.com/cpp/atomic/atomic_init',1,'std']]],
  ['atomic_5fis_5flock_5ffree_102',['atomic_is_lock_free',['https://en.cppreference.com/cpp/atomic/atomic_is_lock_free',1,'std']]],
  ['atomic_5fload_103',['atomic_load',['https://en.cppreference.com/cpp/atomic/atomic_load',1,'std']]],
  ['atomic_5fload_5fexplicit_104',['atomic_load_explicit',['https://en.cppreference.com/cpp/atomic/atomic_load',1,'std']]],
  ['atomic_5fsignal_5ffence_105',['atomic_signal_fence',['https://en.cppreference.com/cpp/atomic/atomic_signal_fence',1,'std']]],
  ['atomic_5fstore_106',['atomic_store',['https://en.cppreference.com/cpp/atomic/atomic_store',1,'std']]],
  ['atomic_5fstore_5fexplicit_107',['atomic_store_explicit',['https://en.cppreference.com/cpp/atomic/atomic_store',1,'std']]],
  ['atomic_5fthread_5ffence_108',['atomic_thread_fence',['https://en.cppreference.com/cpp/atomic/atomic_thread_fence',1,'std']]],
  ['attribute_20bracket_20syntax_109',['Attribute bracket syntax',['../link_handle_reference.html#handle_ref_indexer',1,'']]],
  ['attribute_20vocabulary_110',['pb.hpp Attribute Vocabulary',['../reports_compiler_pb_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20avro_20backend_111',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20bson_20backend_112',['bson:: Attribute Vocabulary (BSON Backend)',['../reports_compiler_bson_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20cbor_20backend_113',['cbor:: Attribute Vocabulary (CBOR Backend)',['../reports_compiler_cbor_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20hdf5_20backend_114',['h5:: Attribute Vocabulary (HDF5 Backend)',['../reports_compiler_h5_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20json_20schema_20backend_115',['json:: Attribute Vocabulary (JSON Schema Backend)',['../reports_compiler_json_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20messagepack_20backend_116',['msgpack:: Attribute Vocabulary (MessagePack Backend)',['../reports_compiler_msgpack_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20rlp_20backend_117',['rlp:: Attribute Vocabulary (RLP Backend)',['../reports_compiler_rlp_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20sql_20backend_118',['sql:: Attribute Vocabulary (SQL Backend)',['../reports_compiler_sql_attribute_taxonomy.html',1,'reports_index']]],
  ['attributes_119',['attributes',['../curated_io_api_attributes.html',1,'ATTRIBUTES'],['../group__attribute-io.html',1,'HDF5 attributes'],['../example_guide_string.html',1,'Strings — VLEN Round-Trip Across Datasets and Attributes']]],
  ['attributes_20—_20metadata_20on_20groups_20and_20datasets_120',['Attributes — Metadata on Groups and Datasets',['../example_guide_attributes.html',1,'examples_guides_index']]],
  ['auto_5fptr_121',['auto_ptr',['https://en.cppreference.com/cpp/memory/auto_ptr/auto_ptr',1,'std::auto_ptr::auto_ptr()'],['https://en.cppreference.com/cpp/memory/auto_ptr',1,'std::auto_ptr']]],
  ['avro_20backend_122',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['avro_3a_3a_20attribute_20vocabulary_20avro_20backend_123',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['awrite_124',['awrite',['../group__attribute-io.html#ga5be7b8b72ad75d37dfc6a2a6823f2219',1,'h5::awrite(const hid_t &amp;parent, const std::string &amp;name, const std::initializer_list&lt; T &gt; ref, const h5::acpl_t &amp;acpl=h5::default_acpl)'],['../group__attribute-io.html#gaa3092182105eac0a0feccca8fb1edec1',1,'h5::awrite(const h5::at_t &amp;attr, const T *ptr)'],['../group__attribute-io.html#ga3991a9abc0c5736ec7c1c754a0e3c0db',1,'h5::awrite(const hid_t &amp;parent, const std::string &amp;name, const T &amp;ref, const h5::acpl_t &amp;acpl=h5::default_acpl)']]]
];
