var searchData=
[
  ['valid_0',['valid',['https://en.cppreference.com/cpp/thread/future/valid',1,'std::future::valid()'],['https://en.cppreference.com/cpp/thread/packaged_task/valid',1,'std::packaged_task::valid()'],['https://en.cppreference.com/cpp/thread/shared_future/valid',1,'std::shared_future::valid()']]],
  ['value_1',['value',['https://en.cppreference.com/cpp/error/error_code/value',1,'std::error_code::value()'],['https://en.cppreference.com/cpp/regex/regex_traits/value',1,'std::regex_traits::value()'],['https://en.cppreference.com/cpp/error/error_condition/value',1,'std::error_condition::value()'],['https://en.cppreference.com/cpp/experimental/optional/value',1,'std::experimental::optional::value()']]],
  ['value_5fcomp_2',['value_comp',['https://en.cppreference.com/cpp/container/multiset/value_comp',1,'std::multiset::value_comp()'],['https://en.cppreference.com/cpp/container/set/value_comp',1,'std::set::value_comp()'],['https://en.cppreference.com/cpp/container/map/value_comp',1,'std::map::value_comp()'],['https://en.cppreference.com/cpp/container/multimap/value_comp',1,'std::multimap::value_comp()']]],
  ['value_5for_3',['value_or',['https://en.cppreference.com/cpp/experimental/optional/value_or',1,'std::experimental::optional']]],
  ['vector_4',['vector',['https://en.cppreference.com/cpp/container/vector/vector',1,'std::vector']]],
  ['vfprintf_5',['vfprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vfscanf_6',['vfscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vfwprintf_7',['vfwprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vfwscanf_8',['vfwscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]],
  ['vprintf_9',['vprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vscanf_10',['vscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vsnprintf_11',['vsnprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vsprintf_12',['vsprintf',['https://en.cppreference.com/cpp/io/c/vfprintf',1,'std']]],
  ['vsscanf_13',['vsscanf',['https://en.cppreference.com/cpp/io/c/vfscanf',1,'std']]],
  ['vswprintf_14',['vswprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vswscanf_15',['vswscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]],
  ['vwprintf_16',['vwprintf',['https://en.cppreference.com/cpp/io/c/vfwprintf',1,'std']]],
  ['vwscanf_17',['vwscanf',['https://en.cppreference.com/cpp/io/c/vfwscanf',1,'std']]]
];
