var searchData=
[
  ['across_20datasets_0',['References — Region &amp; Object Pointers Across Datasets',['../example_guide_reference.html',1,'examples_guides_index']]],
  ['across_20datasets_20and_20attributes_1',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['algebra_2',['LINEAR ALGEBRA',['../curated_topics_linalg.html',1,'curated_topics']]],
  ['algebra_20containers_3',['Linear-Algebra Containers',['../example_guide_linalg.html',1,'examples_guides_index']]],
  ['algebra_20types_4',['Supported Linear Algebra Types',['../link_linalg_template_types.html',1,'']]],
  ['alias_20vocabulary_5',['Doxygen alias vocabulary',['../aliases_reference.html',1,'']]],
  ['analysis_6',['#287 Multithreaded Pipeline — Profile &amp; Analysis',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2multithreaded-pipeline_2profile-report.html',1,'']]],
  ['and_20attributes_7',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['and_20datasets_8',['Attributes — Metadata on Groups and Datasets',['../example_guide_attributes.html',1,'examples_guides_index']]],
  ['and_20handles_9',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['and_20magick_20openexr_20half_20float_20support_10',['Industrial Light and Magick - OpenEXR half float support',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2open-exr_2README.html',1,'']]],
  ['and_20type_20conversion_20callbacks_11',['Transform — DXPL Expressions and Type-Conversion Callbacks',['../example_guide_transform.html',1,'examples_guides_index']]],
  ['api_12',['IO API',['../curated_io_api.html',1,'']]],
  ['append_13',['Packet Tables — Streaming Append',['../example_guide_packet_table.html',1,'examples_guides_index']]],
  ['architecture_14',['architecture',['../curated_topics_architecture.html',1,'ARCHITECTURE'],['../reports_compiler_multi_backend_architecture.html',1,'h5cpp-compiler Multi-Backend Architecture']]],
  ['arguments_20and_20handles_15',['cout — IO-Debug Pretty-Printers for HDF5 Property Lists, Dataspaces, Hyperslab Arguments, and Handles',['../example_guide_cout.html',1,'examples_guides_index']]],
  ['art_20survey_16',['h5cpp-compiler Prior Art Survey',['../reports_compiler_prior_art_survey.html',1,'reports_index']]],
  ['assisted_20hdf5_20serialisation_17',['Reflection — Compiler-Assisted HDF5 Serialisation',['../example_guide_reflection.html',1,'examples_guides_index']]],
  ['attribute_20vocabulary_18',['pb.hpp Attribute Vocabulary',['../reports_compiler_pb_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20avro_20backend_19',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20bson_20backend_20',['bson:: Attribute Vocabulary (BSON Backend)',['../reports_compiler_bson_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20cbor_20backend_21',['cbor:: Attribute Vocabulary (CBOR Backend)',['../reports_compiler_cbor_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20hdf5_20backend_22',['h5:: Attribute Vocabulary (HDF5 Backend)',['../reports_compiler_h5_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20json_20schema_20backend_23',['json:: Attribute Vocabulary (JSON Schema Backend)',['../reports_compiler_json_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20messagepack_20backend_24',['msgpack:: Attribute Vocabulary (MessagePack Backend)',['../reports_compiler_msgpack_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20rlp_20backend_25',['rlp:: Attribute Vocabulary (RLP Backend)',['../reports_compiler_rlp_attribute_taxonomy.html',1,'reports_index']]],
  ['attribute_20vocabulary_20sql_20backend_26',['sql:: Attribute Vocabulary (SQL Backend)',['../reports_compiler_sql_attribute_taxonomy.html',1,'reports_index']]],
  ['attributes_27',['attributes',['../curated_io_api_attributes.html',1,'ATTRIBUTES'],['../example_guide_string.html',1,'Strings — VLEN Round-Trip Across Datasets and Attributes']]],
  ['attributes_20—_20metadata_20on_20groups_20and_20datasets_28',['Attributes — Metadata on Groups and Datasets',['../example_guide_attributes.html',1,'examples_guides_index']]],
  ['avro_20backend_29',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]],
  ['avro_3a_3a_20attribute_20vocabulary_20avro_20backend_30',['avro:: Attribute Vocabulary (Avro Backend)',['../reports_compiler_avro_attribute_taxonomy.html',1,'reports_index']]]
];
