var searchData=
[
  ['s_20reality_0',['h5cpp Type-System Map — Today&apos;s Reality',['../reports_type_system_map.html',1,'reports_index']]],
  ['s3_20example_20—_20read_20only_20s3_20vfd_20ros3_1',['S3 example — Read-Only S3 VFD (ROS3)',['../example_guide_s3.html',1,'examples_guides_index']]],
  ['schema_20backend_2',['json:: Attribute Vocabulary (JSON Schema Backend)',['../reports_compiler_json_attribute_taxonomy.html',1,'reports_index']]],
  ['serialisation_3',['Reflection — Compiler-Assisted HDF5 Serialisation',['../example_guide_reflection.html',1,'examples_guides_index']]],
  ['shapes_4',['Supported container shapes',['../example_guide_container.html',1,'examples_guides_index']]],
  ['showdown_5',['STL Container Showdown',['../example_guide_stl.html',1,'examples_guides_index']]],
  ['single_20writer_20multiple_20reader_6',['SWMR — Single-Writer / Multiple-Reader',['../example_guide_swmr.html',1,'examples_guides_index']]],
  ['smart_20pointer_20support_7',['Smart-Pointer Support',['../example_guide_smart_ptr.html',1,'examples_guides_index']]],
  ['sparse_20matrices_20vectors_20—_20csc_20round_20trip_8',['Sparse Matrices &amp; Vectors — CSC Round-Trip',['../example_guide_sparse.html',1,'examples_guides_index']]],
  ['sql_20backend_9',['sql:: Attribute Vocabulary (SQL Backend)',['../reports_compiler_sql_attribute_taxonomy.html',1,'reports_index']]],
  ['sql_3a_3a_20attribute_20vocabulary_20sql_20backend_10',['sql:: Attribute Vocabulary (SQL Backend)',['../reports_compiler_sql_attribute_taxonomy.html',1,'reports_index']]],
  ['state_20v1_2012_207_11',['h5cpp Multithreaded Filter Pipeline — Current State (v1.12.7)',['../reports_multithreading_pipeline_state.html',1,'reports_index']]],
  ['status_12',['H5CPP Handle Inventory &amp; Pretty-Print Status',['../reports_handle_inventory.html',1,'reports_index']]],
  ['stl_13',['STL',['../curated_topics_stl.html',1,'curated_topics']]],
  ['stl_20container_20showdown_14',['STL Container Showdown',['../example_guide_stl.html',1,'examples_guides_index']]],
  ['stl_20containers_15',['Pretty-Print for STL Containers',['../example_guide_pprint.html',1,'examples_guides_index']]],
  ['stl_20pretty_20print_20guide_16',['H5CPP STL Pretty-Print Guide',['../reports_stl_pretty_print_guide.html',1,'reports_index']]],
  ['stl_20types_17',['Supported STL Types',['../link_stl_template_types.html',1,'']]],
  ['streaming_20append_18',['Packet Tables — Streaming Append',['../example_guide_packet_table.html',1,'examples_guides_index']]],
  ['strings_20—_20vlen_20round_20trip_20across_20datasets_20and_20attributes_19',['Strings — VLEN Round-Trip Across Datasets and Attributes',['../example_guide_string.html',1,'examples_guides_index']]],
  ['support_20',['support',['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2christian-rau_2README.html',1,'half float support'],['../md__2home_2runner_2work_2h5cpp_2h5cpp_2examples_2half-float_2open-exr_2README.html',1,'Industrial Light and Magick - OpenEXR half float support'],['../example_guide_smart_ptr.html',1,'Smart-Pointer Support']]],
  ['supported_20container_20shapes_21',['Supported container shapes',['../example_guide_container.html',1,'examples_guides_index']]],
  ['supported_20linear_20algebra_20types_22',['Supported Linear Algebra Types',['../link_linalg_template_types.html',1,'']]],
  ['supported_20stl_20types_23',['Supported STL Types',['../link_stl_template_types.html',1,'']]],
  ['supported_20types_24',['Supported Types',['../link_base_template_types.html',1,'']]],
  ['surface_25',['UTF-8 — Unicode Throughout the Identifier Surface',['../example_guide_utf.html',1,'examples_guides_index']]],
  ['survey_26',['h5cpp-compiler Prior Art Survey',['../reports_compiler_prior_art_survey.html',1,'reports_index']]],
  ['swmr_20—_20single_20writer_20multiple_20reader_27',['SWMR — Single-Writer / Multiple-Reader',['../example_guide_swmr.html',1,'examples_guides_index']]],
  ['system_20map_20—_20today_20s_20reality_28',['h5cpp Type-System Map — Today&apos;s Reality',['../reports_type_system_map.html',1,'reports_index']]]
];
