// This file was GENERATED by command:
//     pump.py example.cpp.pump
// DO NOT EDIT BY HAND!!!

// Foo0 does blah for 0-ary predicates.template <size_t N >
class Foo0 {  blah a;};
// Foo1 does blah for 1-ary predicates.template <size_t N , typename A1>
class Foo1 {  blah b;};
// Foo2 does blah for 2-ary predicates.template <size_t N , typename A1,
// typename A2>
class Foo2 {  blah b;};
// Foo3 does blah for 3-ary predicates.template <size_t N , typename A1,
// typename A2, typename A3>
class Foo3 {  blah c;};
