var searchData=
[
  ['a_0',['a',['http://en.cppreference.com/w/cpp/numeric/random/extreme_value_distribution/params.html',1,'std::extreme_value_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution/params.html',1,'std::uniform_real_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/weibull_distribution/params.html',1,'std::weibull_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution/params.html',1,'std::uniform_int_distribution::a()'],['http://en.cppreference.com/w/cpp/numeric/random/cauchy_distribution/params.html',1,'std::cauchy_distribution::a()']]],
  ['abort_1',['abort',['http://en.cppreference.com/w/cpp/utility/program/abort.html',1,'std']]],
  ['abs_28float_29_2',['abs(float)',['http://en.cppreference.com/w/cpp/numeric/math/fabs.html',1,'std']]],
  ['abs_28int_29_3',['abs(int)',['http://en.cppreference.com/w/cpp/numeric/math/abs.html',1,'std']]],
  ['accumulate_4',['accumulate',['http://en.cppreference.com/w/cpp/algorithm/accumulate.html',1,'std']]],
  ['acos_5',['acos',['http://en.cppreference.com/w/cpp/numeric/math/acos.html',1,'std']]],
  ['acosh_6',['acosh',['http://en.cppreference.com/w/cpp/numeric/math/acosh.html',1,'std']]],
  ['acpl_7',['template &lt;T&gt; ds_t create( file, path, space [,lcpl] [,dcpl] [,acpl] );',['../group__io-create.html',1,'']]],
  ['add_5fconst_8',['add_const',['http://en.cppreference.com/w/cpp/types/add_cv.html',1,'std']]],
  ['add_5fcv_9',['add_cv',['http://en.cppreference.com/w/cpp/types/add_cv.html',1,'std']]],
  ['add_5flvalue_5freference_10',['add_lvalue_reference',['http://en.cppreference.com/w/cpp/types/add_reference.html',1,'std']]],
  ['add_5fpointer_11',['add_pointer',['http://en.cppreference.com/w/cpp/types/add_pointer.html',1,'std']]],
  ['add_5frvalue_5freference_12',['add_rvalue_reference',['http://en.cppreference.com/w/cpp/types/add_reference.html',1,'std']]],
  ['add_5fvolatile_13',['add_volatile',['http://en.cppreference.com/w/cpp/types/add_cv.html',1,'std']]],
  ['address_14',['address',['http://en.cppreference.com/w/cpp/memory/allocator/address.html',1,'std::allocator']]],
  ['addressof_15',['addressof',['http://en.cppreference.com/w/cpp/memory/addressof.html',1,'std']]],
  ['adjacent_5fdifference_16',['adjacent_difference',['http://en.cppreference.com/w/cpp/algorithm/adjacent_difference.html',1,'std']]],
  ['adjacent_5ffind_17',['adjacent_find',['http://en.cppreference.com/w/cpp/algorithm/adjacent_find.html',1,'std']]],
  ['adopt_5flock_5ft_18',['adopt_lock_t',['http://en.cppreference.com/w/cpp/thread/lock_tag_t.html',1,'std']]],
  ['advance_19',['advance',['http://en.cppreference.com/w/cpp/iterator/advance.html',1,'std']]],
  ['algebra_20types_20',['Supported Linear Algebra Types',['../link_linalg_template_types.html',1,'']]],
  ['align_21',['align',['http://en.cppreference.com/w/cpp/memory/align.html',1,'std']]],
  ['aligned_5fstorage_22',['aligned_storage',['http://en.cppreference.com/w/cpp/types/aligned_storage.html',1,'std']]],
  ['aligned_5funion_23',['aligned_union',['http://en.cppreference.com/w/cpp/types/aligned_union.html',1,'std']]],
  ['alignment_5fof_24',['alignment_of',['http://en.cppreference.com/w/cpp/types/alignment_of.html',1,'std']]],
  ['all_25',['all',['http://en.cppreference.com/w/cpp/utility/bitset/all_any_none.html',1,'std::bitset']]],
  ['all_5fof_26',['all_of',['http://en.cppreference.com/w/cpp/algorithm/all_any_none_of.html',1,'std']]],
  ['allocate_27',['allocate',['http://en.cppreference.com/w/cpp/memory/allocator_traits/allocate.html',1,'std::allocator_traits::allocate()'],['http://en.cppreference.com/w/cpp/memory/allocator/allocate.html',1,'std::allocator::allocate()'],['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor/allocate.html',1,'std::scoped_allocator_adaptor::allocate()']]],
  ['allocate_5fshared_28',['allocate_shared',['http://en.cppreference.com/w/cpp/memory/shared_ptr/allocate_shared.html',1,'std']]],
  ['allocator_29',['allocator',['http://en.cppreference.com/w/cpp/memory/allocator.html',1,'std::allocator'],['http://en.cppreference.com/w/cpp/memory/allocator/allocator.html',1,'std::allocator::allocator()']]],
  ['allocator_5farg_5ft_30',['allocator_arg_t',['http://en.cppreference.com/w/cpp/memory/allocator_arg_t.html',1,'std']]],
  ['allocator_5ftraits_31',['allocator_traits',['http://en.cppreference.com/w/cpp/memory/allocator_traits.html',1,'std']]],
  ['alpha_32',['alpha',['http://en.cppreference.com/w/cpp/numeric/random/gamma_distribution/params.html',1,'std::gamma_distribution']]],
  ['also_20registers_20the_33',['also registers the',['../command.html',1,'']]],
  ['always_5fnoconv_34',['always_noconv',['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',1,'std::codecvt_utf8_utf16::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',1,'std::codecvt::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',1,'std::codecvt_byname::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',1,'std::codecvt_utf16::always_noconv()'],['http://en.cppreference.com/w/cpp/locale/codecvt/always_noconv.html',1,'std::codecvt_utf8::always_noconv()']]],
  ['any_35',['any',['http://en.cppreference.com/w/cpp/utility/bitset/all_any_none.html',1,'std::bitset']]],
  ['any_5fof_36',['any_of',['http://en.cppreference.com/w/cpp/algorithm/all_any_none_of.html',1,'std']]],
  ['append_37',['append',['http://en.cppreference.com/w/cpp/string/basic_string/append.html',1,'std::string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',1,'std::basic_string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',1,'std::wstring::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',1,'std::u16string::append()'],['http://en.cppreference.com/w/cpp/string/basic_string/append.html',1,'std::u32string::append()']]],
  ['array_38',['array',['http://en.cppreference.com/w/cpp/container/array.html',1,'std']]],
  ['array_3c_20hsize_5ft_2c_20h5cpp_5fmax_5frank_20_3e_39',['array&lt; hsize_t, H5CPP_MAX_RANK &gt;',['http://en.cppreference.com/w/cpp/container/array.html',1,'std']]],
  ['array_3c_20impl_3a_3acell_5ft_3c_20t_20_3e_2c_20capacity_5fpow2_20_3e_40',['array&lt; impl::cell_t&lt; T &gt;, capacity_pow2 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',1,'std']]],
  ['array_3c_20impl_3a_3aslot_5ft_3c_20t_20_3e_2c_20capacity_5fpow2_20_3e_41',['array&lt; impl::slot_t&lt; T &gt;, capacity_pow2 &gt;',['http://en.cppreference.com/w/cpp/container/array.html',1,'std']]],
  ['array_3c_20std_3a_3abyte_2c_20n_5fbytes_5fv_20_3e_42',['array&lt; std::byte, n_bytes_v &gt;',['http://en.cppreference.com/w/cpp/container/array.html',1,'std']]],
  ['asctime_43',['asctime',['http://en.cppreference.com/w/cpp/chrono/c/asctime.html',1,'std']]],
  ['asin_44',['asin',['http://en.cppreference.com/w/cpp/numeric/math/asin.html',1,'std']]],
  ['asinh_45',['asinh',['http://en.cppreference.com/w/cpp/numeric/math/asinh.html',1,'std']]],
  ['assign_46',['assign',['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',1,'std::basic_string::assign()'],['http://en.cppreference.com/w/cpp/container/vector/assign.html',1,'std::vector::assign()'],['http://en.cppreference.com/w/cpp/string/char_traits/assign.html',1,'std::char_traits::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',1,'std::string::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',1,'std::regex::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',1,'std::basic_regex::assign()'],['http://en.cppreference.com/w/cpp/regex/basic_regex/assign.html',1,'std::wregex::assign()'],['http://en.cppreference.com/w/cpp/container/forward_list/assign.html',1,'std::forward_list::assign()'],['http://en.cppreference.com/w/cpp/error/error_code/assign.html',1,'std::error_code::assign()'],['http://en.cppreference.com/w/cpp/container/list/assign.html',1,'std::list::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',1,'std::u32string::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',1,'std::u16string::assign()'],['http://en.cppreference.com/w/cpp/error/error_condition/assign.html',1,'std::error_condition::assign()'],['http://en.cppreference.com/w/cpp/utility/functional/function/assign.html',1,'std::function::assign()'],['http://en.cppreference.com/w/cpp/string/basic_string/assign.html',1,'std::wstring::assign()'],['http://en.cppreference.com/w/cpp/container/deque/assign.html',1,'std::deque::assign()']]],
  ['async_47',['async',['http://en.cppreference.com/w/cpp/thread/async.html',1,'std']]],
  ['at_48',['at',['http://en.cppreference.com/w/cpp/string/basic_string/at.html',1,'std::wstring::at()'],['http://en.cppreference.com/w/cpp/container/array/at.html',1,'std::array::at()'],['http://en.cppreference.com/w/cpp/container/map/at.html',1,'std::map::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',1,'std::u32string::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',1,'std::u16string::at()'],['http://en.cppreference.com/w/cpp/container/dynarray/at.html',1,'std::dynarray::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',1,'std::basic_string::at()'],['http://en.cppreference.com/w/cpp/container/vector/at.html',1,'std::vector::at()'],['http://en.cppreference.com/w/cpp/string/basic_string/at.html',1,'std::string::at()'],['http://en.cppreference.com/w/cpp/container/deque/at.html',1,'std::deque::at()'],['http://en.cppreference.com/w/cpp/container/unordered_map/at.html',1,'std::unordered_map::at()']]],
  ['at_5fquick_5fexit_49',['at_quick_exit',['http://en.cppreference.com/w/cpp/utility/program/at_quick_exit.html',1,'std']]],
  ['atan_50',['atan',['http://en.cppreference.com/w/cpp/numeric/math/atan.html',1,'std']]],
  ['atan2_51',['atan2',['http://en.cppreference.com/w/cpp/numeric/math/atan2.html',1,'std']]],
  ['atanh_52',['atanh',['http://en.cppreference.com/w/cpp/numeric/math/atanh.html',1,'std']]],
  ['atexit_53',['atexit',['http://en.cppreference.com/w/cpp/utility/program/atexit.html',1,'std']]],
  ['atof_54',['atof',['http://en.cppreference.com/w/cpp/string/byte/atof.html',1,'std']]],
  ['atoi_55',['atoi',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',1,'std']]],
  ['atol_56',['atol',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',1,'std']]],
  ['atoll_57',['atoll',['http://en.cppreference.com/w/cpp/string/byte/atoi.html',1,'std']]],
  ['atomic_58',['atomic',['http://en.cppreference.com/w/cpp/atomic/atomic/atomic.html',1,'std::atomic::atomic()'],['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std::atomic']]],
  ['atomic_3c_20bool_20_3e_59',['atomic&lt; bool &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_3c_20int_20_3e_60',['atomic&lt; int &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_3c_20std_3a_3asize_5ft_20_3e_61',['atomic&lt; std::size_t &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_3c_20std_3a_3athread_3a_3aid_20_3e_62',['atomic&lt; std::thread::id &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_3c_20std_3a_3auint32_5ft_20_3e_63',['atomic&lt; std::uint32_t &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_3c_20uint32_5ft_20_3e_64',['atomic&lt; uint32_t &gt;',['http://en.cppreference.com/w/cpp/atomic/atomic.html',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fstrong_65',['atomic_compare_exchange_strong',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fstrong_5fexplicit_66',['atomic_compare_exchange_strong_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_67',['atomic_compare_exchange_weak',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',1,'std']]],
  ['atomic_5fcompare_5fexchange_5fweak_5fexplicit_68',['atomic_compare_exchange_weak_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.html',1,'std']]],
  ['atomic_5fexchange_69',['atomic_exchange',['http://en.cppreference.com/w/cpp/atomic/atomic_exchange.html',1,'std']]],
  ['atomic_5fexchange_5fexplicit_70',['atomic_exchange_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_exchange.html',1,'std']]],
  ['atomic_5ffetch_5fadd_71',['atomic_fetch_add',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_add.html',1,'std']]],
  ['atomic_5ffetch_5fadd_5fexplicit_72',['atomic_fetch_add_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_add.html',1,'std']]],
  ['atomic_5ffetch_5fand_73',['atomic_fetch_and',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',1,'std']]],
  ['atomic_5ffetch_5fand_5fexplicit_74',['atomic_fetch_and_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',1,'std']]],
  ['atomic_5ffetch_5for_75',['atomic_fetch_or',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_or.html',1,'std']]],
  ['atomic_5ffetch_5for_5fexplicit_76',['atomic_fetch_or_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_or.html',1,'std']]],
  ['atomic_5ffetch_5fsub_77',['atomic_fetch_sub',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',1,'std']]],
  ['atomic_5ffetch_5fsub_5fexplicit_78',['atomic_fetch_sub_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_sub.html',1,'std']]],
  ['atomic_5ffetch_5fxor_79',['atomic_fetch_xor',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_xor.html',1,'std']]],
  ['atomic_5ffetch_5fxor_5fexplicit_80',['atomic_fetch_xor_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_fetch_xor.html',1,'std']]],
  ['atomic_5fflag_81',['atomic_flag',['http://en.cppreference.com/w/cpp/atomic/atomic_flag/atomic_flag.html',1,'std::atomic_flag::atomic_flag()'],['http://en.cppreference.com/w/cpp/atomic/atomic_flag.html',1,'std::atomic_flag']]],
  ['atomic_5finit_82',['atomic_init',['http://en.cppreference.com/w/cpp/atomic/atomic_init.html',1,'std']]],
  ['atomic_5fis_5flock_5ffree_83',['atomic_is_lock_free',['http://en.cppreference.com/w/cpp/atomic/atomic_is_lock_free.html',1,'std']]],
  ['atomic_5fload_84',['atomic_load',['http://en.cppreference.com/w/cpp/atomic/atomic_load.html',1,'std']]],
  ['atomic_5fload_5fexplicit_85',['atomic_load_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_load.html',1,'std']]],
  ['atomic_5fsignal_5ffence_86',['atomic_signal_fence',['http://en.cppreference.com/w/cpp/atomic/atomic_signal_fence.html',1,'std']]],
  ['atomic_5fstore_87',['atomic_store',['http://en.cppreference.com/w/cpp/atomic/atomic_store.html',1,'std']]],
  ['atomic_5fstore_5fexplicit_88',['atomic_store_explicit',['http://en.cppreference.com/w/cpp/atomic/atomic_store.html',1,'std']]],
  ['atomic_5fthread_5ffence_89',['atomic_thread_fence',['http://en.cppreference.com/w/cpp/atomic/atomic_thread_fence.html',1,'std']]],
  ['auto_5fptr_90',['auto_ptr',['http://en.cppreference.com/w/cpp/memory/auto_ptr/auto_ptr.html',1,'std::auto_ptr::auto_ptr()'],['http://en.cppreference.com/w/cpp/memory/auto_ptr.html',1,'std::auto_ptr']]]
];
